theme:           jekyll-theme-cayman
title:           Guess the Image
description:     Try to recognize the partially visible images
is_user_page:    false
is_project_page: true
show_downloads:  true
